In [5]:
import numpy as np

In [8]:
l = [1,2,3,"guru",5]

In [9]:
type(l)

list

In [11]:
np.array(l)

array(['1', '2', '3', 'guru', '5'], dtype='<U11')

In [14]:
type(np.array(l))

numpy.ndarray

In [15]:
np.array([1,2,3,4,5.0])

array([1., 2., 3., 4., 5.])

In [16]:
np.array([1,2,3,4,5.1])

array([1. , 2. , 3. , 4. , 5.1])

In [18]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [20]:
a=np.array([[1,2],[3,4]])

In [21]:
a[0]

array([1, 2])

In [22]:
a[0,1]

2

In [25]:
a[1,1]

4

In [26]:
a[1][1]

4

In [27]:
#Watched till 1 hour 19 mins (12 march)

In [28]:
a2 = np.array([1,2,3,4],ndmin = 4)

In [34]:
a2

array([[[[1, 2, 3, 4]]]])

In [35]:
a2[0,0,0,1]

2

In [36]:
a2[0][0][0][1]

2

In [46]:
a2[0][0][0][3]

4

In [50]:
a3 = np.array([[1,2],[3,4]])

In [51]:
a3

array([[1, 2],
       [3, 4]])

In [52]:
a3[0,1]

2

In [53]:
a3[0,0]

1

In [56]:
a3[0,1]

2

In [57]:
a3[1,0]

3

In [58]:
a3[1,1]

4

In [59]:
np.asanyarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [60]:
np.asanyarray([1,2,3,4,5,'Gur'])

array(['1', '2', '3', '4', '5', 'Gur'], dtype='<U11')

In [62]:
mat = np.mat([1,2,3])

In [63]:
mat[0,0]

1

In [72]:
mat[0,1]

2

In [78]:
mt = np.mat([1,2,3,4,5])

In [84]:
mt[0,1]

2

In [85]:
mt[0,0]

1

In [86]:
arr = np.array([1,2,3,4])

In [88]:
arr[1]

2

In [89]:
a = [1,2,3,4,5]

In [90]:
np.asarray(a)

array([1, 2, 3, 4, 5])

In [91]:
np.mat(a)

matrix([[1, 2, 3, 4, 5]])

In [92]:
np.asanyarray(a)

array([1, 2, 3, 4, 5])

In [93]:
np.asanyarray(np.mat(a))

matrix([[1, 2, 3, 4, 5]])

In [94]:
a

[1, 2, 3, 4, 5]

In [95]:
np.fromfunction(lambda i, j : i == j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [96]:
np.fromfunction(lambda i, j : i == j,(2,3))

array([[ True, False, False],
       [False,  True, False]])

In [98]:
np.fromfunction(lambda i, j : i == j,(2,2))

array([[ True, False],
       [False,  True]])

In [99]:
np.fromfunction(lambda i, j : i == j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [100]:
np.fromfunction(lambda i, j : i*j,(4,4))

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.],
       [0., 3., 6., 9.]])

In [103]:
np.fromfunction(lambda i, j : i*j,(4,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 1, 2, 3],
       [0, 2, 4, 6],
       [0, 3, 6, 9]])

In [104]:
np.mat(np.fromfunction(lambda i, j : i*j,(4,4),dtype=int))

matrix([[0, 0, 0, 0],
        [0, 1, 2, 3],
        [0, 2, 4, 6],
        [0, 3, 6, 9]])

In [107]:
np.mat(np.fromfunction(lambda i, j, z : i*j*z,(3,3,3),dtype=int))

ValueError: shape too large to be a matrix.

In [108]:
np.fromfunction(lambda i, j, z : i*j*z,(3,3,3),dtype=int)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 1, 2],
        [0, 2, 4]],

       [[0, 0, 0],
        [0, 2, 4],
        [0, 4, 8]]])

In [109]:
np.fromfunction(lambda i, j, z : i*j*z,(3,3,2),dtype=int)

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]]])

In [113]:
np.fromfunction(lambda i, j, z : i*j*z,(4,3,2),dtype=int)

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [114]:
np.fromfunction(lambda i, j, z, p : i*j*z*p,(4,3,2,2),dtype=int)

array([[[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 1]],

        [[0, 0],
         [0, 2]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 2]],

        [[0, 0],
         [0, 4]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 3]],

        [[0, 0],
         [0, 6]]]])