In [5]:
import numpy as np

In [8]:
l = [1,2,3,"guru",5]

In [9]:
type(l)

list

In [11]:
np.array(l)

array(['1', '2', '3', 'guru', '5'], dtype='<U11')

In [14]:
type(np.array(l))

numpy.ndarray

In [15]:
np.array([1,2,3,4,5.0])

array([1., 2., 3., 4., 5.])

In [16]:
np.array([1,2,3,4,5.1])

array([1. , 2. , 3. , 4. , 5.1])

In [18]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [20]:
a=np.array([[1,2],[3,4]])

In [21]:
a[0]

array([1, 2])

In [22]:
a[0,1]

2

In [25]:
a[1,1]

4

In [26]:
a[1][1]

4

In [27]:
#Watched till 1 hour 19 mins (12 march)

In [28]:
a2 = np.array([1,2,3,4],ndmin = 4)

In [34]:
a2

array([[[[1, 2, 3, 4]]]])

In [35]:
a2[0,0,0,1]

2

In [36]:
a2[0][0][0][1]

2

In [46]:
a2[0][0][0][3]

4

In [50]:
a3 = np.array([[1,2],[3,4]])

In [51]:
a3

array([[1, 2],
       [3, 4]])

In [52]:
a3[0,1]

2

In [53]:
a3[0,0]

1

In [56]:
a3[0,1]

2

In [57]:
a3[1,0]

3

In [58]:
a3[1,1]

4

In [59]:
np.asanyarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [60]:
np.asanyarray([1,2,3,4,5,'Gur'])

array(['1', '2', '3', '4', '5', 'Gur'], dtype='<U11')

In [62]:
mat = np.mat([1,2,3])

In [63]:
mat[0,0]

1

In [72]:
mat[0,1]

2

In [78]:
mt = np.mat([1,2,3,4,5])

In [84]:
mt[0,1]

2

In [85]:
mt[0,0]

1

In [86]:
arr = np.array([1,2,3,4])

In [88]:
arr[1]

2

In [89]:
a = [1,2,3,4,5]

In [90]:
np.asarray(a)

array([1, 2, 3, 4, 5])

In [91]:
np.mat(a)

matrix([[1, 2, 3, 4, 5]])

In [92]:
np.asanyarray(a)

array([1, 2, 3, 4, 5])

In [93]:
np.asanyarray(np.mat(a))

matrix([[1, 2, 3, 4, 5]])

In [94]:
a

[1, 2, 3, 4, 5]

In [95]:
np.fromfunction(lambda i, j : i == j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [96]:
np.fromfunction(lambda i, j : i == j,(2,3))

array([[ True, False, False],
       [False,  True, False]])

In [98]:
np.fromfunction(lambda i, j : i == j,(2,2))

array([[ True, False],
       [False,  True]])

In [99]:
np.fromfunction(lambda i, j : i == j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [100]:
np.fromfunction(lambda i, j : i*j,(4,4))

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.],
       [0., 3., 6., 9.]])

In [103]:
np.fromfunction(lambda i, j : i*j,(4,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 1, 2, 3],
       [0, 2, 4, 6],
       [0, 3, 6, 9]])

In [104]:
np.mat(np.fromfunction(lambda i, j : i*j,(4,4),dtype=int))

matrix([[0, 0, 0, 0],
        [0, 1, 2, 3],
        [0, 2, 4, 6],
        [0, 3, 6, 9]])

In [107]:
np.mat(np.fromfunction(lambda i, j, z : i*j*z,(3,3,3),dtype=int))

ValueError: shape too large to be a matrix.

In [108]:
np.fromfunction(lambda i, j, z : i*j*z,(3,3,3),dtype=int)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 1, 2],
        [0, 2, 4]],

       [[0, 0, 0],
        [0, 2, 4],
        [0, 4, 8]]])

In [109]:
np.fromfunction(lambda i, j, z : i*j*z,(3,3,2),dtype=int)

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]]])

In [113]:
np.fromfunction(lambda i, j, z : i*j*z,(4,3,2),dtype=int)

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [114]:
np.fromfunction(lambda i, j, z, p : i*j*z*p,(4,3,2,2),dtype=int)

array([[[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 1]],

        [[0, 0],
         [0, 2]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 2]],

        [[0, 0],
         [0, 4]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 3]],

        [[0, 0],
         [0, 6]]]])

In [116]:
a = np.fromfunction(lambda i, j, z, p : i*j*z*p,(4,3,2,2),dtype=int)

In [117]:
a.ndim

4

In [118]:
a.size

48

In [119]:
a.shape

(4, 3, 2, 2)

In [120]:
a.dtype

dtype('int32')

In [121]:
a

array([[[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 1]],

        [[0, 0],
         [0, 2]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 2]],

        [[0, 0],
         [0, 4]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 3]],

        [[0, 0],
         [0, 6]]]])

In [6]:
import pandas as pd 

In [125]:
a = np.fromfunction(lambda i, j : i*j,(4,3),dtype=int)

In [126]:
a

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4],
       [0, 3, 6]])

In [127]:
pd.DataFrame(a)

0  1  2
0  0  0  0
1  0  1  2
2  0  2  4
3  0  3  6

In [128]:
a

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4],
       [0, 3, 6]])

In [129]:
np.random.rand()

0.2706377636351034

In [131]:
np.random.rand(100,4)

array([[0.47621968, 0.8168029 , 0.76059228, 0.32872136],
       [0.31097312, 0.79753488, 0.12878815, 0.33558925],
       [0.42571863, 0.30515552, 0.57588466, 0.01838942],
       [0.30758383, 0.13124518, 0.86092476, 0.54051224],
       [0.21040928, 0.1877024 , 0.57587585, 0.70728097],
       [0.20515434, 0.25878378, 0.90061698, 0.2803746 ],
       [0.82195868, 0.13946478, 0.62552122, 0.18692599],
       [0.2467997 , 0.87303193, 0.65816981, 0.0676803 ],
       [0.80289743, 0.64972886, 0.31759746, 0.7185243 ],
       [0.1772142 , 0.77816632, 0.03679165, 0.47148557],
       [0.92138589, 0.75344897, 0.62858158, 0.49507145],
       [0.99644619, 0.18284388, 0.7110825 , 0.73386422],
       [0.77307006, 0.33011283, 0.05916489, 0.36962036],
       [0.63848974, 0.92584338, 0.44239501, 0.44845979],
       [0.94781225, 0.90114086, 0.28902968, 0.17140913],
       [0.80954122, 0.08968678, 0.89279652, 0.51313077],
       [0.64520964, 0.68629735, 0.1984798 , 0.40492083],
       [0.73222167, 0.49477398,

In [140]:
np.random.randint(1,50)

33

In [141]:
np.random.randn(4,5)

array([[ 0.17181821,  0.82757938,  0.16288037,  0.90099218, -0.65510415],
       [-1.2281642 ,  0.109257  , -2.11770842, -0.6564711 ,  1.29750912],
       [ 0.8837862 ,  0.22139379, -0.41852733, -0.24892671,  0.50482202],
       [ 1.95505451, -0.14470197, -1.09200614,  0.16792648, -1.405102  ]])

In [142]:
pd.DataFrame(np.random.randn(4,5))

0         1         2         3         4
0 -0.233641  0.983339  3.016378  0.493224  0.234653
1  0.565510 -2.035354 -0.083317 -0.837748  0.410470
2 -1.751349 -0.400066  1.506847 -0.645522 -0.231020
3 -0.414534 -1.045384  0.136348  0.380826  0.958913

In [1]:
list(range(4,10))

[4, 5, 6, 7, 8, 9]

In [2]:
list(range(4,10,2))

[4, 6, 8]

In [8]:
np.arange(4,10)

array([4, 5, 6, 7, 8, 9])

In [11]:
np.arange(-1,10,.2)

array([-1.00000000e+00, -8.00000000e-01, -6.00000000e-01, -4.00000000e-01,
       -2.00000000e-01, -2.22044605e-16,  2.00000000e-01,  4.00000000e-01,
        6.00000000e-01,  8.00000000e-01,  1.00000000e+00,  1.20000000e+00,
        1.40000000e+00,  1.60000000e+00,  1.80000000e+00,  2.00000000e+00,
        2.20000000e+00,  2.40000000e+00,  2.60000000e+00,  2.80000000e+00,
        3.00000000e+00,  3.20000000e+00,  3.40000000e+00,  3.60000000e+00,
        3.80000000e+00,  4.00000000e+00,  4.20000000e+00,  4.40000000e+00,
        4.60000000e+00,  4.80000000e+00,  5.00000000e+00,  5.20000000e+00,
        5.40000000e+00,  5.60000000e+00,  5.80000000e+00,  6.00000000e+00,
        6.20000000e+00,  6.40000000e+00,  6.60000000e+00,  6.80000000e+00,
        7.00000000e+00,  7.20000000e+00,  7.40000000e+00,  7.60000000e+00,
        7.80000000e+00,  8.00000000e+00,  8.20000000e+00,  8.40000000e+00,
        8.60000000e+00,  8.80000000e+00,  9.00000000e+00,  9.20000000e+00,
        9.40000000e+00,  

In [13]:
np.arange(-10,10)

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9])

In [14]:
arr = np.random.rand(4,5)

In [15]:
arr

array([[0.43559475, 0.71997353, 0.32506324, 0.27053003, 0.62726717],
       [0.54727424, 0.87659526, 0.9158668 , 0.18056211, 0.88316402],
       [0.43180625, 0.33997354, 0.6649005 , 0.72035383, 0.01256941],
       [0.10202257, 0.54766734, 0.05356013, 0.44002526, 0.26350015]])

In [19]:
arr > .5

array([[False,  True, False, False,  True],
       [ True,  True,  True, False,  True],
       [False, False,  True,  True, False],
       [False,  True, False, False, False]])

In [20]:
 arr[arr > .5]

array([0.71997353, 0.62726717, 0.54727424, 0.87659526, 0.9158668 ,
       0.88316402, 0.6649005 , 0.72035383, 0.54766734])

In [21]:
arr

array([[0.43559475, 0.71997353, 0.32506324, 0.27053003, 0.62726717],
       [0.54727424, 0.87659526, 0.9158668 , 0.18056211, 0.88316402],
       [0.43180625, 0.33997354, 0.6649005 , 0.72035383, 0.01256941],
       [0.10202257, 0.54766734, 0.05356013, 0.44002526, 0.26350015]])

In [29]:
arr[1,2]  

0.9158667951624168

In [30]:
arr[2,2]


0.6649004983507226

In [31]:
arr[[1,2]]

array([[0.54727424, 0.87659526, 0.9158668 , 0.18056211, 0.88316402],
       [0.43180625, 0.33997354, 0.6649005 , 0.72035383, 0.01256941]])

In [33]:
arr[[1,2],[2,2]]

array([0.9158668, 0.6649005])

In [34]:
arr = np.random.rand(8,5)

In [35]:
arr

array([[0.48581661, 0.05489053, 0.07717233, 0.40327384, 0.48609519],
       [0.6746138 , 0.48581914, 0.52578477, 0.82567463, 0.89916085],
       [0.71821287, 0.66056105, 0.48648465, 0.03273505, 0.30830763],
       [0.36749181, 0.81262267, 0.22834633, 0.85128785, 0.01957108],
       [0.19707643, 0.82478629, 0.44067977, 0.57100951, 0.23844419],
       [0.04909558, 0.89053111, 0.59482717, 0.56707327, 0.78347141],
       [0.09818856, 0.3755947 , 0.13735094, 0.80088705, 0.79129656],
       [0.62522359, 0.21909084, 0.26465392, 0.06000005, 0.80785933]])

In [36]:
arr[1]

array([0.6746138 , 0.48581914, 0.52578477, 0.82567463, 0.89916085])

In [37]:
arr[1,3]

0.8256746328537928

In [43]:
arr[1:8,[0,1,2]]

array([[0.6746138 , 0.48581914, 0.52578477],
       [0.71821287, 0.66056105, 0.48648465],
       [0.36749181, 0.81262267, 0.22834633],
       [0.19707643, 0.82478629, 0.44067977],
       [0.04909558, 0.89053111, 0.59482717],
       [0.09818856, 0.3755947 , 0.13735094],
       [0.62522359, 0.21909084, 0.26465392]])

In [44]:
a2 = arr[1:8,[0,1,2]]

In [45]:
a2

array([[0.6746138 , 0.48581914, 0.52578477],
       [0.71821287, 0.66056105, 0.48648465],
       [0.36749181, 0.81262267, 0.22834633],
       [0.19707643, 0.82478629, 0.44067977],
       [0.04909558, 0.89053111, 0.59482717],
       [0.09818856, 0.3755947 , 0.13735094],
       [0.62522359, 0.21909084, 0.26465392]])

In [46]:
a2[0][0]

0.6746138019003869

In [51]:
a2[0][0] = 100

In [52]:
a2

array([[1.00000000e+02, 4.85819136e-01, 5.25784775e-01],
       [7.18212866e-01, 6.60561046e-01, 4.86484653e-01],
       [3.67491809e-01, 8.12622669e-01, 2.28346327e-01],
       [1.97076433e-01, 8.24786289e-01, 4.40679770e-01],
       [4.90955798e-02, 8.90531110e-01, 5.94827171e-01],
       [9.81885629e-02, 3.75594699e-01, 1.37350940e-01],
       [6.25223593e-01, 2.19090836e-01, 2.64653917e-01]])

In [57]:
a = np.array([[1,2],[3,4]])

In [58]:
b = np.array([[2,3],[4,5]])

In [59]:
a

array([[1, 2],
       [3, 4]])

In [60]:
b

array([[2, 3],
       [4, 5]])

In [61]:
a * b

array([[ 2,  6],
       [12, 20]])

In [62]:
a@b

array([[10, 13],
       [22, 29]])

In [63]:
m\0

SyntaxError: unexpected character after line continuation character (282590415.py, line 1)

In [67]:
m = a@b

In [68]:
m

array([[10, 13],
       [22, 29]])

In [69]:
m/0

C:\Users\gsingh\AppData\Local\Temp\ipykernel_13332\3791875896.py:1: RuntimeWarning: divide by zero encountered in true_divide
  m/0


array([[inf, inf],
       [inf, inf]])